### ISSUE TITLE
Implement more structured internal data structure for object model

### ISSUE THREAD

**Issue by ben-mental-fitness** [davehenryjones/WellbeingJam2020#21]
Implement a structured storage model for nodes on the visualisation (to allow for easier manipulation of elements). This may be dependent on the use case so needs to be discussed in more detail.

**Comment by davehenryjones** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement more structure internal data structure for object model](https://trello.com/c/0uXf5HpR/36-implement-more-structure-internal-data-structure-for-object-model)

**Comment by ben-mental-fitness** [comment]
Fixed for current use case.
