### ISSUE TITLE
Postcodes to co-ordinate API

### ISSUE THREAD

**Issue by ben-mental-fitness** [davehenryjones/WellbeingJam2020#9]
Use an API to convert postcodes to co-ordinates

**Comment by davehenryjones** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [postcodes to co-ordinate API](https://trello.com/c/pfBMWYAM/41-postcodes-to-co-ordinate-api)

**Comment by davehenryjones** [comment]
Done in davehenryjones.github.io/pavedev2 needs verification
